language: node_js
node_js:
  - "12"

sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.27.4

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose up -d --build
after_script:
  - docker-compose down
addons:
  jwt:
    secure: NJ3XZTGwiws2HqViPToNAXk/OBGGsXc7PoOk8N4ZANoqpTxWhnR1lNeDHcePu3HaFxpO9XZ5HCNjKq1qAzHyEhaIv4HpCbIzp9A6olR1F0/UvNluyj9QQc0O1gZ1sL3XSKugG7VxmqWziCPRcQwads1FmKMSyurSbVWQnVnCvQiNbxuamuboepCXvDe45/B6/QmL8gfSgrHZN9NkzbIOkFoIBfNG6JPam4nhgRNJ/mweyTIoZ0FK2tr3BXwoQCNsE0oT4M9KoyfhH9oRbE+fLfvDkPC0OsNGj5wtdCrExn9DW8kEZWoqA+kFa/u3g3H2VsV4vWs/pelJECz+chfhHYjMkzvt/R3OHIY8xFVPgnUwO8ZenrtUhLLJiSwRQfzwG8oNjwA7++5UbQpQbvrKgXVZ+pRfBijsh4NCeE2fmoecf2JiGV0pDPDXyF8rK2DTtbLNZU2YfLTarL5AC0OS/0imCRQNORyZg90l48PYLFGF0ztKZrZxRF1PuwKpG+7ZAvah8QsON/hLZZQYbWsok0MUQgVBRug3grU2m/9GRF+i4zpt4BYthve9RxwXQEM9eflBFOldDjWTPBTaDbjpvC7+Cn9ZrMW6SqnmwUqok0S2Sm+WWpNp7JJJZUF0w4pl1PHuZFiohtP00KZbJGwbYYZTZNQgvBnMQejLaX9o7AY=
script:
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: LHsGaZCn87E5KArjwHipWwzqZqDOeKKZ8p2z3RR46acr48h+ZJan18AzULH69iYwMQUCHEdH0TV4oqrslsnGPCBNWWwAsVc2ecw1Ohwyb7+gKh4+lI4zrNzYHRBVID8gJ0H2Tp8KQHc3Xh96V8CIPmIlsDIbyaOnI2fe0A/GxBEBzU79cHi0EySDi9YjflDVvg9rT1aDU5exRfOEU4C9HUxF8cZfiTciio7rAY3aEcjZHvYtISQDxlDLYNpxnBcVhJOGoqaf8fCxaYj0SsAqZT8ISqlOzvoF3TXOR+EpS8/zz503bCQ6NFrkDE2uFLje8HYkcQt8NgF2umbFR2RzCenp9LbDKSTmBE3o8YuSI6ErMGIJYI+wyRMK4Jy5mzMvTUHhRXZqZIA+eRvcz0vGK3lzX3/T7ZT4YBfVJPOxQZX815jrH9bdWL1onRVoUr4v0x8vWj0jPfKUXYeNJNSexfv5qWlCN64uWfsjPvhbg8MYE82no5wxwOQNt4vZV8JgNDIuzYJBXqer17GxZCxPjatpcdeLZNJgtCEi4B7QxoZ3n7tDBMoP8hjv9xFc5B0ju9gVj9CvG4ugVYolUdCOdjrgBKsh2QBByAgX/RmNG6ejoucG3AWCGn/VmEEW0aeW7QA9FNIOzOogEVCmZRqRzPxiblqOgxiSyrJh4nkmTh8=
  app: theamtest
  on:
    repo: albacruz/Theam-Test
  skip_cleanup: true
