version: "3.8"
services:
  api-core:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env.docker
  postgresql:
    image: postgres:12.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env
volumes:
  postgres-data:
    external: false
