version: "3.8"
services:
  api-core:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: database
  postgresql:
    image: postgres:12.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=theamshop
      - POSTGRES_USER=albacruz
      - POSTGRES_PASSWORD=pwd0123456789
volumes:
  postgres-data:
    external: false
