# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Integration/Acceptance tests
    runs-on: ubuntu-latest
    container: node:12-alpine
    services:
      database:
        image: postgres:12.2-alpine
        env:
          POSTGRES_DB: theamshop
          POSTGRES_USER: albacruz
          POSTGRES_PASSWORD: pwd0123456789
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Tests
        run: npm run test -- --runInBand
        env:
          DATABASE_HOST: database
          TYPEORM_DATABASE: theamshop
          TYPEORM_USERNAME: albacruz
          TYPEORM_PASSWORD: pwd0123456789
